### ISSUE TITLE
Support path token types in macro

### ISSUE THREAD

**Issue by resinten** [Emerentius/partial_application#1]
I have a static function on `MyStruct` called `initialize` with 3 arguments. It seems that it does not work with the `partial!` macro:

```
partial!(MyStruct::initialize(x, y, _);
```

It seems to get confused by the `_` in this situation and looks for an expression there.

**Comment by Emerentius** [comment]
It seems you are missing an ending parenthesis. The syntax is either `partial!(function(args...))` or `partial!(function args...)`

**Comment by resinten** [comment]
Ah, yes, my example above still has a typo. The issue still exists for me though. Here is a simple example I put together just now. The last line causes a compilation error. If you remove it, the rest works fine.
```
#[macro_use]
extern crate partial_application;

#[derive(Debug)]
struct Foobar {
    x: &'static str,
    y: i32,
    z: bool,
}

impl Foobar {
    fn initialize(x: &'static str, y: i32, z: bool) -> Self {
        Foobar { x, y, z }
    }
}

fn hello_world(name: &str, other: i32) {
    println!("{}, your number is {}", name, other);
}

fn main() {
    println!("Hello, world!");

    hello_world("Foo", 32);
    partial!(hello_world("Bar", _))(64);
    partial!(hello_world "Baz", _)(128);

    println!("Qux: {:?}", Foobar::initialize("Qux", 1, false));
    println!("Quux: {:?}", partial!(Foobar::initialize("Quux", 2, _))(true));
}
```

**Comment by Emerentius** [comment]
A minimal example is
```
#[macro_use]
extern crate partial_application;

fn foo() {
    partial!(::foo());
}
```

and the problematic code is this:
```rust
macro_rules! partial {
    …
    ($id:ident $($args:tt)*) => …
}
```

I only just now realized what you meant with the name of this issue. I'm getting the function name by matching an identifier token, but you're passing a path. I'm not sure how to fix it right now, as of all the [metavariables](https://doc.rust-lang.org/reference/macros-by-example.html#metavariables) I'm allowed to match on, the most fitting (`path`) is forbidden to be followed by `(` in my matching clause. Same with `expr`. `tt` causes an ambiguity with the following `$args`.

The error is misleading, it really misparsed everything up to that last argument already.

**Comment by Emerentius** [comment]
`path` is actually not suited for this either as this does not parse as a path: `Vec::<i32>::new`. Leaves only `expr` and rustc has this to say:

```
`$id:expr` is followed by `(`, which is not allowed for `expr` fragments

not allowed after `expr` fragments

note: allowed there are: `=>`, `,` or `;`
```

So I guess I'll just have to require a `,` and/or `;` in between the function and its arguments. Don't think `=>` is fitting here. I'm leaning towards `,` for uniformity with the arg list.

**Comment by Emerentius** [comment]
I just went for allowing all three of them. This changes the syntax to `partial!(Vec::with_capacity => 2)`. I'm hoping I can switch back to 0.1.0 syntax in the future with a better macro system. I don't want to use the current procedural macros with `syn` as that balloons compile times too much for a micro crate such as this.

**Comment by nordzilla** [comment]
> I just went for allowing all three of them. This changes the syntax to `partial!(Vec::with_capacity => 2)`. I'm hoping I can switch back to 0.1.0 syntax in the future with a better macro system. I don't want to use the current procedural macros with `syn` as that balloons compile times too much for a micro crate such as this.

I know I'm 5 years late to the party here, but I was recently implementing a macro very similar to this for fun. After I was finished I had a look at this crate to see what approaches other people had taken. 

There is probably a way that you can still have your `0.1.0` syntax even with a declarative macro, and also maintain backward compatibility with the current version/syntax. 

Right now you have these entry points:

```rust
    ($id:expr , $($args:tt)*)
    ($id:expr ; $($args:tt)*)
    ($id:expr => $($args:tt)*)
```

I think you should be able to do all of these as well:

```rust
    (($($id:tt)+) ($($args:tt)*))
    ([$($id:tt)+] ($($args:tt)*))
    ({$($id:tt)+} ($($args:tt)*))

    ($id:ident ($($args:tt)*))
```

In that way, if you only have an identifier as your function, you should be able to call the `$id:ident` version:

```rust
partial!(foo(_, 5, _));
```

And if you have something more complicated than an ident, you could do any of:

```rust
partial!(Vec::<u32>::push ; _, 5);
partial!(Vec::<u32>::push , _, 5);
partial!(Vec::<u32>::push => _, 5);

partial!((Vec::<u32>::push)(_, 5)); // <--- This one looks nicest to me.
partial!([Vec::<u32>::push](_, 5));
partial!({Vec::<u32>::push}(_, 5));
```

The internals of your macro would all use one of the `$($id:tt)+` options, but both of the `$id:expr` and `$id:ident` entry points should be able to pass to the `$($id:tt)+` internals.

---

Just an extra thought as well, in the version that I implemented, I found that it was nice to offer the syntax of `_` for an unapplied, anonymous argument, just as you have done, but I also found it convenient to offer the pattern of `arg_name: {}` as well, which would then give that name to the argument in the resulting closure. 

For example, all of these could be valid syntax. 

```rust
partial!(foo(x: {}, y: 5, z: {});
partial!(foo(x: {}, 5, z: {});
partial!(foo(x: {}, 5, _);
partial!(foo(_, y, _);
```

I found that this worked nicely with rust analyzer, which provides the names of the arguments when invoking the closure. 

---

Lastly, here is the macro that I ended up with, for context. It's a bit different than yours in style, but nearly identical in what it does, though I didn't handle anything with `move`.  

```rust
macro_rules! pfa {
    (($($name:tt)+)($($args:tt)*)) => {
        pfa!({$($name)+} Arg { $($args)* } -> (
            AllArgs {}
            UnknownArgs {}
        ))
    };

    (($($name:tt)+)({$($args:tt)*})) => {
        pfa!({$($name)+} Arg { $($args)* } -> (
            AllArgs {}
            UnknownArgs {}
        ))
    };

    ($name:ident($($args:tt)*)) => {
        pfa!({$name} Arg { $($args)* } -> (
            AllArgs {}
            UnknownArgs {}
        ))
    };

    ({$($name:tt)+} Arg { $value:expr, $($args:tt)+ } -> (
        AllArgs { $($all:tt)* }
        UnknownArgs { $($unknown:tt)* }
    )) => {
        pfa!({$($name)+} Arg { $($args)* } -> (
            AllArgs { $($all)* $value, }
            UnknownArgs { $($unknown)* }
        ))
    };

    ({$($name:tt)+} Arg { $value:expr $(,)? } -> (
        AllArgs { $($all:tt)* }
        UnknownArgs { $($unknown:tt)* }
    )) => {
        pfa!({$($name)+} Arg { } -> (
            AllArgs { $($all)* $value, }
            UnknownArgs { $($unknown)* }
        ))
    };

    ({$($name:tt)+} Arg { $arg:ident : {}, $($args:tt)+ } -> (
        AllArgs { $($all:tt)* }
        UnknownArgs { $($unknown:tt)* }
    )) => {
        pfa!({$($name)+} Arg { $($args)* } -> (
            AllArgs { $($all)* $arg, }
            UnknownArgs { $($unknown)* $arg, }
        ))
    };

    ({$($name:tt)+} Arg { $arg:ident : {} $(,)? } -> (
        AllArgs { $($all:tt)* }
        UnknownArgs { $($unknown:tt)* }
    )) => {
        pfa!({$($name)+} Arg { } -> (
            AllArgs { $($all)* $arg, }
            UnknownArgs { $($unknown)* $arg, }
        ))
    };

    ({$($name:tt)+} Arg { $arg:ident : $value:expr, $($args:tt)+ } -> (
        AllArgs { $($all:tt)* }
        UnknownArgs { $($unknown:tt)* }
    )) => {
        pfa!({$($name)+} Arg { $($args)* } -> (
            AllArgs { $($all)* $value, }
            UnknownArgs { $($unknown)* }
        ))
    };

    ({$($name:tt)+} Arg { $arg:ident : $value:expr $(,)? } -> (
        AllArgs { $($all:tt)* }
        UnknownArgs { $($unknown:tt)* }
    )) => {
        pfa!({$($name)+} Arg { } -> (
            AllArgs { $($all)* $value, }
            UnknownArgs { $($unknown)* }
        ))
    };

    ({$($name:tt)+} Arg { _, $($args:tt)+ } -> (
        AllArgs { $($all:tt)* }
        UnknownArgs { $($unknown:tt)* }
    )) => {
        pfa!({$($name)+} Arg { $($args)* } -> (
            AllArgs { $($all)* arg, }
            UnknownArgs { $($unknown)* arg, }
        ))
    };

    ({$($name:tt)+} Arg { _ $(,)? } -> (
        AllArgs { $($all:tt)* }
        UnknownArgs { $($unknown:tt)* }
    )) => {
        pfa!({$($name)+} Arg { } -> (
            AllArgs { $($all)* arg, }
            UnknownArgs { $($unknown)* arg, }
        ))
    };

    ({$($name:tt)+} Arg {} -> (
        AllArgs { $($all:tt)* }
        UnknownArgs { $($unknown:tt)* }
    )) => {
        |$($unknown)*| $($name)+($($all)*)
    }
}
```
